name: Build and compress DCT binary

on:
  push:
    branches:
      - master 

jobs:
  build: 
    name: Build and Compress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build DCT
        run: | 
          go mod tidy
          CGO_ENABLED=0 go build -ldflags="-s -w -extldflags '-static'" -o dct
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -extldflags '-static'" -o dct-darwin-arm64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -extldflags '-static'" -o dct-linux-arm64
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -extldflags '-static'" -o dct-win-amd64.exe

      - name: Install UPX
        run: | 
          sudo apt-get update
          sudo apt-get install upx -y

      - name: Compress Binary
        run: | 
          upx --best --lzma ./dct
          upx --best --lzma ./dct-darwin-arm64 --force-macos
          upx --best --lzma ./dct-linux-arm64
          upx --best --lzma ./dct-win-amd64.exe

      - name: Upload Compressed amd64 Binary
        uses: actions/upload-artifact@v4
        with:
          name: dct-linux-amd64
          path: ./dct

      - name: Upload Compressed Linux arm64 Binary
        uses: actions/upload-artifact@v4
        with:
          name: dct-linux-arm64
          path: ./dct-linux-arm64

      - name: Upload Compressed Mac Binary
        uses: actions/upload-artifact@v4
        with:
          name: dct-darwin-arm64
          path: ./dct-darwin-arm64

      - name: Upload Compressed Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: dct-win-amd64.exe
          path: ./dct-win-amd64.exe