name: Build and compress DCT binary

on:
  workflow_dispatch: 

jobs:
  build: 
    name: Build and Compress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build DCT
        run: | 
          go mod tidy
          CGO_ENABLED=0 go build -ldflags="-s -w -extldflags '-static'"

      - name: Install UPX
        run: | 
          sudo apt-get update
           sudo apt-get install upx -y

      - name: Compress Binary
        run: | 
          upx --best --lzma ./dct

      - name: Upload Compressed Binary
        uses: actions/upload-artifact@v4
        with:
          name: ./dct